# Generated by Django 2.2.7 on 2019-12-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engName', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('atomicNum', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
