# Generated by Django 2.2.7 on 2019-12-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='appearance',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='element',
            name='atomic_num',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='element',
            name='block',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='element',
            name='boiling_point_celsius',
            field=models.DecimalField(decimal_places=15, default=1.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='element',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='element',
            name='critical_point',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='element',
            name='density_at_STP',
            field=models.DecimalField(decimal_places=15, default=1.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='element',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='discoverer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='element',
            name='electron_configuration',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='element',
            name='electron_configuration_full',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='element',
            name='en_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='group',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='element',
            name='heat_of_fusion',
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='element',
            name='heat_of_vaporization',
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='element',
            name='melting_point_celsius',
            field=models.DecimalField(decimal_places=15, default=1.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='element',
            name='period',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='element',
            name='phase_at_STP',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='element',
            name='standard_atomic_weight',
            field=models.DecimalField(decimal_places=15, default=1.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='element',
            name='triple_point',
            field=models.DecimalField(decimal_places=15, default=1.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='element',
            name='year_discovered',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
