# Generated by Django 2.2.7 on 2019-12-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptable', '0002_auto_20191216_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='atomicNum',
            new_name='atomic_num',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='engName',
            new_name='en_name',
        ),
    ]
