# Generated by Django 2.2.7 on 2019-12-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptable', '0003_auto_20191216_0525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='atomic_num',
            new_name='atomicNum',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='en_name',
            new_name='engName',
        ),
    ]
