# Generated by Django 2.2.7 on 2019-12-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptable', '0004_auto_20191217_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='appearance',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='element',
            name='block',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='element',
            name='category',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='element',
            name='discoverer',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='element',
            name='electron_configuration',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='element',
            name='electron_configuration_full',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='element',
            name='phase_at_STP',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
