# Generated by Django 2.2.7 on 2019-12-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptable', '0005_auto_20191221_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='symbol',
            field=models.CharField(default='', max_length=2),
        ),
    ]
